# Generated by Django 5.1.7 on 2025-03-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'name')},
        ),
    ]
