# Generated by Django 5.1.7 on 2025-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='photos/'),
        ),
    ]
