# Generated by Django 5.1.7 on 2025-04-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='elections/'),
        ),
    ]
