# Generated by Django 5.1.7 on 2025-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_election_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, default='default-candidate.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='election',
            name='photo',
            field=models.ImageField(blank=True, default='default-election.jpg', null=True, upload_to='photos/'),
        ),
    ]
